from unittest import TestCase

from it_depends.ubuntu.apt import file_to_packages


class TestAPT(TestCase):
    def test_file_to_package(self) -> None:
        assert file_to_packages("/usr/bin/python3") == [
            "python3-activipy",
            "python3-commonmark",
            "python3-coverage",
            "python3-coverage",
            "python3-cymruwhois",
            "python3-dbg",
            "python3-dbg",
            "python3-dbg",
            "python3-dbg",
            "python3-dev",
            "python3-future",
            "python3-future",
            "python3-memory-profiler",
            "python3-minimal",
            "python3-nopie",
            "python3-petname",
            "python3-pysaml2",
            "python3-pysaml2",
            "python3-pysaml2",
            "python3-pysaml2",
            "python3-qrcode",
            "python3-stem",
            "python3-unidiff",
            "python3-unittest2",
            "python3.10-dbg",
            "python3.10-dbg",
            "python3.10-dbg",
            "python3.10-dbg",
            "python3.10-dbg",
            "python3.10-dbg",
            "python3.10-dbg",
            "python3.10-dbg",
            "python3.10-dbg",
            "python3.10-dev",
            "python3.10-minimal",
            "python3.10-nopie",
            "python3.11-dbg",
            "python3.11-dbg",
            "python3.11-dbg",
            "python3.11-dbg",
            "python3.11-dbg",
            "python3.11-dbg",
            "python3.11-dbg",
            "python3.11-dbg",
            "python3.11-dev",
            "python3.11-minimal",
            "python3.11-nopie",
        ]
