version: '3.8'

services:

  db:
    image: neo4j:4.0.10
    # image: neo4j:3.5.26
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - 7474:7474
      - 7687:7687
