#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

which flake8 >/dev/null 2>/dev/null
RESULT=$?
if [ $RESULT -ne 0 ]; then
  cat << \EOF
flake8 is not installed! Run this from the root of the it-depends repo:

    pip3 install -e .[dev]
EOF
  exit 1
fi

echo Linting Python code...
flake8 it_depends test --count --select=E9,F63,F7,F82 --show-source --statistics 1>/dev/null 2>/dev/null
RESULT=$?
if [ $RESULT -ne 0 ]; then
  cat <<\EOF
Failed Python lint:

    flake8 it_depends test --count --select=E9,F63,F7,F82 --show-source --statistics
EOF
  exit 1
fi

flake8 it_depends test --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 1>/dev/null 2>/dev/null
RESULT=$?
if [ $RESULT -ne 0 ]; then
  cat <<\EOF
Failed Python lint:

    flake8 it_depends test --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
EOF
  exit 1
fi

which mypy >/dev/null 2>/dev/null
RESULT=$?
if [ $RESULT -ne 0 ]; then
  cat << \EOF
mypy is not installed! Run this from the root of the it-depends repo:

    pip3 install -e .[dev]
EOF
  exit 1
fi

# echo Type-checking Python code...
# mypy --ignore-missing-imports it_depends test
# RESULT=$?
# if [ $RESULT -ne 0 ]; then
#   exit $RESULT
# fi

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against --
